# 入力ファイル
INPUT_FILE: data/参加者アンケート.xlsx
# 出力ファイル
OUTPUT_FILE: data/result.csv
# テンプレートファイル
TEMPLATE_FILE: data/template.txt
# チャンクサイズ（一度に処理する件数を指定します。AI呼び出しがエラーになった場合に、処理結果が失われるため、ある程度の件数ごとに処理することを推奨。）
CHUNK_SIZE: 100
# 開始位置（処理の開始位置。この値以上のNUMBER_LOCが処理対象となります。）
START_POSITION: 1
# モデルID
MODEL_ID: anthropic.claude-v2
# Excelファイルの入力ファイルのキーの位置（例では、アンケート回収時に連番が自動的に付与されます。）
NUMBER_LOC: 0
# Excelファイル中の値の位置（例では、アンケートの回答）
VALUE_LOC: 1